### ISSUE TITLE
Issues with Disqus

### ISSUE THREAD

**Issue by YusufRWeb** [YusufRWeb/YusufRWeb.github.io#1]
@spikespaz  I just thought I would let you know:
* Disqus doesn't  load on the [test website](https://yusufrweb.github.io/) or the [original website](https://cmdiscord.github.io/).
* If you want to fix this, go ahead, otherwise we can solve it later.

![Happy](https://discordapp.com/assets/b731b88b6459090c02b8d1e31a552c5a.svg)

**Comment by spikespaz** [comment]
I know.
